### ISSUE TITLE
Update zegami channel in Anaconda

### ISSUE THREAD

**Issue by mratsim** [zegami/pillow-simd-conda#1]
Your channel didn't seem to get your latest github updates:

This https://anaconda.org/zegami/pillow-simd displays the wrong version for Linux and MacOS:
![image](https://user-images.githubusercontent.com/22738317/32973326-1b2afaa4-cbf7-11e7-9ba9-6824dee8c2f7.png)

And installing requires Python 3.5.2:
```
$  conda install -c zegami pillow-simd
Fetching package metadata .................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pillow-simd -> python 3.5.2*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

Note: that's the second day I use conda so I may have missed something.

**Comment by RogerNoble** [comment]
Hi
We haven't yet created updated builds for Linux and MaxOS.
